# Buổi 04 - Bài 03 - Bài Tập (Phần 01)

- MSSV: 25410291
- Họ Tên: Đinh Xuân Sâm
- GDrive: [IE313-b04-bai03-baitap.ipynb](https://colab.research.google.com/drive/1fOgSMdDqFqAD0m8OnZbixeKjQhqUt4kB?usp=drive_link)

## Yêu Cầu

- Đưa vào một df và tên quốc gia cụ thể.
- Trả về số lượng di cư của quốc gia đó tới Canada
- Các cột từ 1980 - 2013
- Mỗi cột là một năm
- Thêm cột tổng số ở cuối

## Nạp Dữ Liệu

In [7]:
# Khai báo tên của dataset trước khi tải về
canada_dataset_url = "https://github.com/datasethub/ds105/raw/refs/heads/master/Canada.xlsx"
canada_dataset_file = "Canada.xlsx"

In [8]:
# Tải dataset
import requests

response = requests.get(canada_dataset_url)

with open(canada_dataset_file, "wb") as file:
    file.write(response.content)

print("Download complete!")

Download complete!

In [9]:
# cài đặt xlrd
!pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [10]:
# import
import pandas as pd
import numpy as np

In [11]:
# đọc file excel
df_canada = pd.read_excel(
    canada_dataset_file,
    sheet_name='Canada by Citizenship',
    skiprows=range(20),
    skipfooter=2
)

df_canada.shape

(195, 43)

In [14]:
# thông tin của dataset
df_canada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 43 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Type      195 non-null    object
 1   Coverage  195 non-null    object
 2   OdName    195 non-null    object
 3   AREA      195 non-null    int64
 4   AreaName  195 non-null    object
 5   REG       195 non-null    int64
 6   RegName   195 non-null    object
 7   DEV       195 non-null    int64
 8   DevName   195 non-null    object
 9   1980      195 non-null    int64
 10  1981      195 non-null    int64
 11  1982      195 non-null    int64
 12  1983      195 non-null    int64
 13  1984      195 non-null    int64
 14  1985      195 non-null    int64
 15  1986      195 non-null    int64
 16  1987      195 non-null    int64
 17  1988      195 non-null    int64
 18  1989      195 non-null    int64
 19  1990      195 non-null    int64
 20  1991      195 non-null    int64
 21  1992      195 non-null    int64
 22  1993      195 non-null    int64
 23  1994      195 non-null    int64
 24  1995      195 non-null    int64
 25  1996      195 non-null    int64
 26  1997      195 non-null    int64
 27  1998      195 non-null    int64
 28  1999      195 non-null    int64
 29  2000      195 non-null    int64
 30  2001      195 non-null    int64
 31  2002      195 non-null    int64
 32  2003      195 non-null    int64
 33  2004      195 non-null    int64
 34  2005      195 non-null    int64
 35  2006      195 non-null    int64
 36  2007      195 non-null    int64
 37  2008      195 non-null    int64
 38  2009      195 non-null    int64
 39  2010      195 non-null    int64
 40  2011      195 non-null    int64
 41  2012      195 non-null    int64
 42  2013      195 non-null    int64
dtypes: int64(37), object(6)
memory usage: 65.6+ KB

In [19]:
# xem thử
df_canada.sample()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
40,Immigrants,Foreigners,Comoros,903,Africa,910,Eastern Africa,902,Developing regions,0,...,6,5,7,11,3,19,22,14,18,22

## Bài Làm

### Đổi Tên Cột

In [21]:
# khai báo danh sách cột đổi cũ: mới
columns = {
    'OdName': 'Country',
    'AreaName': 'Continent',
    'RegName': 'Region'
}

# kiểm thử sau khi đổi
df_canada.rename(columns=columns, inplace=False).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 43 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Type       195 non-null    object
 1   Coverage   195 non-null    object
 2   Country    195 non-null    object
 3   AREA       195 non-null    int64
 4   Continent  195 non-null    object
 5   REG        195 non-null    int64
 6   Region     195 non-null    object
 7   DEV        195 non-null    int64
 8   DevName    195 non-null    object
 9   1980       195 non-null    int64
 10  1981       195 non-null    int64
 11  1982       195 non-null    int64
 12  1983       195 non-null    int64
 13  1984       195 non-null    int64
 14  1985       195 non-null    int64
 15  1986       195 non-null    int64
 16  1987       195 non-null    int64
 17  1988       195 non-null    int64
 18  1989       195 non-null    int64
 19  1990       195 non-null    int64
 20  1991       195 non-null    int64
 21  1992       195 non-null    int64
 22  1993       195 non-null    int64
 23  1994       195 non-null    int64
 24  1995       195 non-null    int64
 25  1996       195 non-null    int64
 26  1997       195 non-null    int64
 27  1998       195 non-null    int64
 28  1999       195 non-null    int64
 29  2000       195 non-null    int64
 30  2001       195 non-null    int64
 31  2002       195 non-null    int64
 32  2003       195 non-null    int64
 33  2004       195 non-null    int64
 34  2005       195 non-null    int64
 35  2006       195 non-null    int64
 36  2007       195 non-null    int64
 37  2008       195 non-null    int64
 38  2009       195 non-null    int64
 39  2010       195 non-null    int64
 40  2011       195 non-null    int64
 41  2012       195 non-null    int64
 42  2013       195 non-null    int64
dtypes: int64(37), object(6)
memory usage: 65.6+ KB

In [25]:
# thực hiện và kiểm lại
df_canada.rename(columns=columns, inplace=True)
df_canada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 43 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Type       195 non-null    object
 1   Coverage   195 non-null    object
 2   Country    195 non-null    object
 3   AREA       195 non-null    int64
 4   Continent  195 non-null    object
 5   REG        195 non-null    int64
 6   Region     195 non-null    object
 7   DEV        195 non-null    int64
 8   DevName    195 non-null    object
 9   1980       195 non-null    int64
 10  1981       195 non-null    int64
 11  1982       195 non-null    int64
 12  1983       195 non-null    int64
 13  1984       195 non-null    int64
 14  1985       195 non-null    int64
 15  1986       195 non-null    int64
 16  1987       195 non-null    int64
 17  1988       195 non-null    int64
 18  1989       195 non-null    int64
 19  1990       195 non-null    int64
 20  1991       195 non-null    int64
 21  1992       195 non-null    int64
 22  1993       195 non-null    int64
 23  1994       195 non-null    int64
 24  1995       195 non-null    int64
 25  1996       195 non-null    int64
 26  1997       195 non-null    int64
 27  1998       195 non-null    int64
 28  1999       195 non-null    int64
 29  2000       195 non-null    int64
 30  2001       195 non-null    int64
 31  2002       195 non-null    int64
 32  2003       195 non-null    int64
 33  2004       195 non-null    int64
 34  2005       195 non-null    int64
 35  2006       195 non-null    int64
 36  2007       195 non-null    int64
 37  2008       195 non-null    int64
 38  2009       195 non-null    int64
 39  2010       195 non-null    int64
 40  2011       195 non-null    int64
 41  2012       195 non-null    int64
 42  2013       195 non-null    int64
dtypes: int64(37), object(6)
memory usage: 65.6+ KB

### Loại Bỏ Cột

In [26]:
# danh sách các cột cần bỏ
drop_collumns = ['AREA', 'REG', 'DEV', 'Type', 'Coverage']

# kiểm thử
df_canada.drop(columns=drop_collumns, inplace=False).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 38 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    195 non-null    object
 1   Continent  195 non-null    object
 2   Region     195 non-null    object
 3   DevName    195 non-null    object
 4   1980       195 non-null    int64
 5   1981       195 non-null    int64
 6   1982       195 non-null    int64
 7   1983       195 non-null    int64
 8   1984       195 non-null    int64
 9   1985       195 non-null    int64
 10  1986       195 non-null    int64
 11  1987       195 non-null    int64
 12  1988       195 non-null    int64
 13  1989       195 non-null    int64
 14  1990       195 non-null    int64
 15  1991       195 non-null    int64
 16  1992       195 non-null    int64
 17  1993       195 non-null    int64
 18  1994       195 non-null    int64
 19  1995       195 non-null    int64
 20  1996       195 non-null    int64
 21  1997       195 non-null    int64
 22  1998       195 non-null    int64
 23  1999       195 non-null    int64
 24  2000       195 non-null    int64
 25  2001       195 non-null    int64
 26  2002       195 non-null    int64
 27  2003       195 non-null    int64
 28  2004       195 non-null    int64
 29  2005       195 non-null    int64
 30  2006       195 non-null    int64
 31  2007       195 non-null    int64
 32  2008       195 non-null    int64
 33  2009       195 non-null    int64
 34  2010       195 non-null    int64
 35  2011       195 non-null    int64
 36  2012       195 non-null    int64
 37  2013       195 non-null    int64
dtypes: int64(34), object(4)
memory usage: 58.0+ KB

In [27]:
# thực hiện
df_canada.drop(columns=drop_collumns, inplace=True)
df_canada.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 38 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    195 non-null    object
 1   Continent  195 non-null    object
 2   Region     195 non-null    object
 3   DevName    195 non-null    object
 4   1980       195 non-null    int64
 5   1981       195 non-null    int64
 6   1982       195 non-null    int64
 7   1983       195 non-null    int64
 8   1984       195 non-null    int64
 9   1985       195 non-null    int64
 10  1986       195 non-null    int64
 11  1987       195 non-null    int64
 12  1988       195 non-null    int64
 13  1989       195 non-null    int64
 14  1990       195 non-null    int64
 15  1991       195 non-null    int64
 16  1992       195 non-null    int64
 17  1993       195 non-null    int64
 18  1994       195 non-null    int64
 19  1995       195 non-null    int64
 20  1996       195 non-null    int64
 21  1997       195 non-null    int64
 22  1998       195 non-null    int64
 23  1999       195 non-null    int64
 24  2000       195 non-null    int64
 25  2001       195 non-null    int64
 26  2002       195 non-null    int64
 27  2003       195 non-null    int64
 28  2004       195 non-null    int64
 29  2005       195 non-null    int64
 30  2006       195 non-null    int64
 31  2007       195 non-null    int64
 32  2008       195 non-null    int64
 33  2009       195 non-null    int64
 34  2010       195 non-null    int64
 35  2011       195 non-null    int64
 36  2012       195 non-null    int64
 37  2013       195 non-null    int64
dtypes: int64(34), object(4)
memory usage: 58.0+ KB

In [34]:
# liệt kê tên các nước để đảm bảo gọi đúng tên
# ví dụ Viet Nam thay vì Vietnam, hay vietnam, vv..
df_canada['Country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China',
       'China, Hong Kong Special Administrative Region',
       'China, Macao Special Administrative Region', 'Colombia',
       'Comoros', 'Congo', 'Costa Rica', "Côte d'Ivoire", 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'State of Palestine', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The former Yugoslav Republic of Macedonia', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Western Sahara',
       'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

### Tạo Hàm Chọn

In [107]:
# Đưa vào một df và tên quốc gia cụ thể.
# Trả về số lượng di cư của quốc gia đó tới Canada
# Các cột từ 1980 - 2013
# Mỗi cột là một năm
# Thêm cột tổng số ở cuối

def chon(df: pd.DataFrame, Country: str) -> pd.Series:
    # chọn ra quốc gia và tạo bản sao
    df_chon = df.loc[df['Country'] == Country].copy()
    # lấy các cột năm (các cột có name là số)
    years = [col_name for col_name in df.columns.to_list() if isinstance(col_name, int)]
    # tính tổng từ các năm và gán cột total
    df_chon['total'] = df_chon[years].sum(axis=1)
    # trả về series
    return df_chon

In [108]:
# Kiểm thử

chon(df_canada, 'Viet Nam')

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,total
190,Viet Nam,Asia,South-Eastern Asia,Developing regions,1191,1829,2162,3404,7583,5907,...,1852,3153,2574,1784,2171,1942,1723,1731,2112,97146

### Hoàn Thành

- Hàm `chon()` đã được hoàn thành.
- Nhận vào `pd.DataFrame` và một tên nước.
- Trả về một `pd.Series` chứa dòng của nước đó, kèm một cột tổng.